### ISSUE TITLE
Recurring error in logs

### ISSUE THREAD

**Issue by JC-Mac** [molobrakos/volvooncall#9]
Hi! 

I am trying to get volvooncall working in my HA (0.51.1 on docker).  If I enable debug, I see a successful login to the VOC servers, and successful retrieval of lots of car data .. however, nothing showing in HA.  I see the following recurring error in logs and wonder if this is the issue: 

2017-08-14 20:56:13 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 180, in _step
    result = coro.send(None)
  File "/usr/src/app/homeassistant/helpers/entity.py", line 205, in async_update_ha_state
    "No entity id specified for entity {}".format(self.name))
  File "/usr/src/app/homeassistant/components/volvooncall.py", line 157, in name
    self._vehicle_name,
  File "/usr/src/app/homeassistant/components/volvooncall.py", line 146, in _vehicle_name
    self.vehicle.registration_number.lower()) or
AttributeError: 'NoneType' object has no attribute 'lower'
2017-08-14 20:56:13 ERROR (MainThread) [homeassistant.core] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/app/homeassistant/components/device_tracker/volvooncall.py", line 28, in see_vehicle
    dev_id = 'volvo_{}'.format(slugify(host_name))
  File "/usr/src/app/homeassistant/util/__init__.py", line 42, in slugify
    text = normalize('NFKD', text)
TypeError: normalize() argument 2 must be str, not None

My config.yaml:
#Volvo
volvooncall:
  username: myusername
  password: !secret volvo_pwd
  service_url: 'https://vocapi-na.wirelesscar.net/customerapi/rest/v3.0/'

Thanks!

**Comment by molobrakos** [comment]
I could not reproduce it in the 0.52 development version (dev branch of HA).
- Can you run the standalone 'voc' script from this library, like 'voc status'?
- In the "successful retrieval of lots of car data" that you mention when running HA - is the registration number of the car present? Does it contain any special characters (other than alphanumeric)?

**Comment by JC-Mac** [comment]
Hi Erik!  Thank you tremendously for the reply.  

Doesn't look like the registration is returning anything: 

 'registrationNumber': None,

Full info returned for the vehicle is pasted below (although I obfuscated teh VIN).  

Not quite sure how to run standalone voc or voc status ... I have cloned the repository, and can see that voc is executable, but can't seem to figure out how to run it.  Sorry, could you be a little more explicit (running on Ubuntu). 

2017-08-14 21:02:31 DEBUG (SyncWorker_5) [volvooncall] State: {'https://vocapi-na.wirelesscar.net/customerapi/rest/v3.0/vehicles/YVmyVIN#/': {'engineCode': '2421CF0B', 'exteriorCode': '2421110B', 'interiorCode': '24211005', 'tyreDimensionCode': '2421R509', 'tyreInflationPressureLightCode': None, 'tyreInflationPressureHeavyCode': None, 'gearboxCode': '2421DB01', 'fuelType': 'HEV', 'fuelTankVolume': 50, 'grossWeight': 3010, 'modelYear': 2016, 'vehicleType': 'XC90', 'vehicleTypeCode': '2421AA04', 'numberOfDoors': 5, 'country': {'iso2': 'CA'}, 'registrationNumber': None, 'carLocatorDistance': 1000, 'honkAndBlinkDistance': 500, 'bCallAssistanceNumber': '+18553994691', 'carLocatorSupported': True, 'honkAndBlinkSupported': True, 'honkAndBlinkVersionsSupported': ['honkAndOrBlink', 'honkAndBlink'], 'remoteHeaterSupported': False, 'unlockSupported': True, 'lockSupported': True, 'journalLogSupported': True, 'assistanceCallSupported': True, 'unlockTimeFrame': 120, 'verificationTimeFrame': 120, 'timeFullyAccessible': 7200, 'timePartiallyAccessible': 31680, 'subscriptionType': 'PREMIUM_2013', 'subscriptionStartDate': datetime.datetime(2016, 5, 20, 12, 0, tzinfo=datetime.timezone.utc), 'subscriptionEndDate': datetime.datetime(2017, 11, 22, 12, 59, 7, tzinfo=datetime.timezone.utc), 'serverVersion': '4.10.11-voc-deployable', 'VIN': 'YVmyVIN#', 'journalLogEnabled': True, 'highVoltageBatterySupported': True, 'overrideDelayChargingSupported': False, 'maxActiveDelayChargingLocations': 7, 'preclimatizationSupported': True, 'sendPOIToVehicleVersionsSupported': ['sendSinglePOIToVehicle'], 'climatizationCalendarVersionsSupported': ['climatizationCalendarV1'], 'climatizationCalendarMaxTimers': 8, 'vehiclePlatform': '2421', 'vin': 'YVmyVIN#', 'engineStartSupported': True, 'status.parkedIndoor.supported': False, 'ERS': {'status': None, 'timestamp': None, 'engineStartWarning': None, 'engineStartWarningTimestamp': None}, 'averageFuelConsumption': 67.0, 'averageFuelConsumptionTimestamp': datetime.datetime(2017, 8, 14, 11, 43, 14, tzinfo=datetime.timezone.utc), 'averageSpeed': 50, 'averageSpeedTimestamp': datetime.datetime(2017, 8, 14, 11, 43, 14, tzinfo=datetime.timezone.utc), 'brakeFluid': 'Normal', 'brakeFluidTimestamp': datetime.datetime(2017, 8, 14, 11, 43, 14, tzinfo=datetime.timezone.utc), 'bulbFailures': [], 'bulbFailuresTimestamp': datetime.datetime(2017, 8, 14, 11, 43, 14, tzinfo=datetime.timezone.utc), 'carLocked': True, 'carLockedTimestamp': datetime.datetime(2017, 8, 14, 11, 43, 14, tzinfo=datetime.timezone.utc), 'connectionStatus': 'Disconnected', 'connectionStatusTimestamp': datetime.datetime(2017, 8, 14, 11, 43, 21, tzinfo=datetime.timezone.utc), 'distanceToEmpty': 450, 'distanceToEmptyTimestamp': datetime.datetime(2017, 8, 14, 11, 43, 14, tzinfo=datetime.timezone.utc), 'doors': {'tailgateOpen': False, 'rearRightDoorOpen': False, 'rearLeftDoorOpen': False, 'frontRightDoorOpen': False, 'frontLeftDoorOpen': False, 'hoodOpen': False, 'timestamp': datetime.datetime(2017, 8, 14, 11, 43, 14, tzinfo=datetime.timezone.utc)}, 'engineRunning': False, 'engineRunningTimestamp': datetime.datetime(2017, 8, 14, 11, 43, 14, tzinfo=datetime.timezone.utc), 'fuelAmount': 38, 'fuelAmountLevel': 76, 'fuelAmountLevelTimestamp': datetime.datetime(2017, 8, 14, 11, 43, 14, tzinfo=datetime.timezone.utc), 'fuelAmountTimestamp': datetime.datetime(2017, 8, 14, 11, 43, 14, tzinfo=datetime.timezone.utc), 'heater': {'seatSelection': {'frontDriverSide': False, 'frontPassengerSide': False, 'rearDriverSide': False, 'rearPassengerSide': False, 'rearMid': False}, 'status': 'off', 'timer1': {'time': None, 'state': None}, 'timer2': {'time': None, 'state': None}, 'timestamp': datetime.datetime(2017, 6, 19, 12, 7, 14, tzinfo=datetime.timezone.utc)}, 'hvBattery': {'hvBatteryChargeStatusDerived': 'CableNotPluggedInCar', 'hvBatteryChargeStatusDerivedTimestamp': datetime.datetime(2017, 8, 14, 11, 43, 21, tzinfo=datetime.timezone.utc), 'hvBatteryChargeModeStatus': None, 'hvBatteryChargeModeStatusTimestamp': None, 'hvBatteryChargeStatus': 'PlugRemoved', 'hvBatteryChargeStatusTimestamp': datetime.datetime(2017, 8, 13, 18, 21, 14, tzinfo=datetime.timezone.utc), 'hvBatteryLevel': 90, 'hvBatteryLevelTimestamp': datetime.datetime(2017, 8, 14, 11, 43, 21, tzinfo=datetime.timezone.utc), 'distanceToHVBatteryEmpty': None, 'distanceToHVBatteryEmptyTimestamp': datetime.datetime(2017, 8, 14, 11, 43, 21, tzinfo=datetime.timezone.utc), 'hvBatteryChargeWarning': 'UnexpectedPowerloss', 'hvBatteryChargeWarningTimestamp': datetime.datetime(2017, 8, 10, 19, 46, 28, tzinfo=datetime.timezone.utc), 'timeToHVBatteryFullyCharged': 60, 'timeToHVBatteryFullyChargedTimestamp': datetime.datetime(2017, 8, 13, 15, 32, 31, tzinfo=datetime.timezone.utc)}, 'odometer': 11452667, 'odometerTimestamp': datetime.datetime(2017, 8, 14, 11, 43, 14, tzinfo=datetime.timezone.utc), 'remoteClimatizationStatus': 'NoCableConnected', 'remoteClimatizationStatusTimestamp': datetime.datetime(2017, 8, 14, 11, 43, 21, tzinfo=datetime.timezone.utc), 'serviceWarningStatus': 'Normal', 'serviceWarningStatusTimestamp': datetime.datetime(2017, 8, 14, 11, 43, 14, tzinfo=datetime.timezone.utc), 'timeFullyAccessibleUntil': datetime.datetime(2017, 8, 19, 11, 42, 13, tzinfo=datetime.timezone.utc), 'timePartiallyAccessibleUntil': datetime.datetime(2017, 9, 5, 11, 42, 13, tzinfo=datetime.timezone.utc), 'tripMeter1': 3453000, 'tripMeter1Timestamp': datetime.datetime(2017, 8, 14, 11, 43, 14, tzinfo=datetime.timezone.utc), 'tripMeter2': 100, 'tripMeter2Timestamp': datetime.datetime(2017, 8, 14, 11, 43, 14, tzinfo=datetime.timezone.utc), 'tyrePressure': {'frontLeftTyrePressure': 'Normal', 'frontRightTyrePressure': 'Normal', 'rearLeftTyrePressure': 'Normal', 'rearRightTyrePressure': 'Normal', 'timestamp': datetime.datetime(2017, 8, 14, 11, 43, 14, tzinfo=datetime.timezone.utc)}, 'washerFluidLevel': 'Normal', 'washerFluidLevelTimestamp': datetime.datetime(2017, 8, 14, 11, 43, 14, tzinfo=datetime.timezone.utc), 'windows': {'frontLeftWindowOpen': False, 'frontRightWindowOpen': False, 'timestamp': datetime.datetime(2017, 8, 14, 11, 43, 14, tzinfo=datetime.timezone.utc), 'rearLeftWindowOpen': False, 'rearRightWindowOpen': False}, 'position': {'longitude': -73.59344482421875, 'latitude': 45.47975158691406, 'timestamp': datetime.datetime(2017, 8, 14, 11, 42, 14, tzinfo=datetime.timezone.utc), 'speed': None, 'heading': None}, 'calculatedPosition': {'longitude': None, 'latitude': None, 'timestamp': None, 'speed': None, 'heading': None}}}
\

**Comment by molobrakos** [comment]
Ok, it seems we can not rely on registration number being present then.
Here is a fix to HA:
https://github.com/molobrakos/home-assistant/commit/366227c4848d50f975df4103185d2709840e150c
Maybe you can try to make this change locally and test it before I submit it (I tested it by mock-removing the returned registration number for my car)?

Btw, how to run voc locally on Ubuntu:
```
$ pip3 install --user volvooncall
$ ~/.local/bin/voc -vv -u <username> -p <password> status
```

**Comment by JC-Mac** [comment]
Modification worked perfectly! - I now have all sorts of great info from the car showing in my HA states.  Thank you so much!  Tremendously appreciated!  Cheers, I owe you a pint or 3!

**Comment by JC-Mac** [comment]
Might need a similar adustment in the volvooncall tracker too:

 File "/usr/src/app/homeassistant/components/device_tracker/volvooncall.py", line 28, in see_vehicle dev_id = 'volvo_{}'.format(slugify(host_name)) File "/usr/src/app/homeassistant/util/__init__.py", line 42, in slugify text = normalize('NFKD', text) TypeError: normalize() argument 2 must be str, not None

**Comment by molobrakos** [comment]
Ah, missed that, thanks. I believe this is also fixed now (had to rewrite some more stuff). Seems to work, so I will submit this as a PR then.
https://github.com/molobrakos/home-assistant/commit/ff0fd3532a6e68080483c29fc5cb3db8c359dafe
